### ISSUE TITLE
Video 9 & 10 Kaha Gayi

### ISSUE THREAD

**Issue by cleverhare** [CodeWithHarry/Sigma-Web-Dev-Course#10]
Harry Bhai, You forgot to add source code of 9th and 10th video of SIGMA OP COURSE

**Comment by Vivaan1st** [comment]
HTML

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Youtube 2.0</title>
    <link rel="stylesheet" href="Website.css">
</head>
<body>
    <header>
        <nav>
            <h1>Home</h1>
        </nav>
    </header>
    <main>
        <h2>About Harry</h2>
    <p>Harry is a Programmer, Web Developer, Web Developer Educator, and Youtube Video Creator. The name of his YouTube channel is Code With Harry. People also know him by the name of Harris Ali Khan. Harry is a resident of Rampur Uttar Pradesh. He has completed his studies at IIT Kharagpur. On YouTube, he teaches coding to people in a very easy way. Their method of teaching is so easy that anyone can learn coding easily.

    Code with Harry is a YouTube Channel Owned by Harris Ali Khan. Code With Harry regularly posts programming videos in Hindu languages and every content gets a good response from fans. Because of his way of talking, quality of content everything is fantastic. That's why most Technical persons subscribe to his channel to watch the latest tech videos.
    </p>
    <h2>Learn HTML AND CSS BY CODE WITH HARRY </h2>
    <p>Zero Junction to Hero Junction,Hurry up train will be starting soon!!</p>
    
    <iframe width="560" height="315" src="https://www.youtube.com/embed/tVzUXW6siu0?si=mzI-avXpalTw-aT9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/kJEsTjH5mVg?si=5rASFCaBB_qFEFJ0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/BGeDBfCIqas?si=7oG4sug97ojXHrs8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/nXba2-mgn1k?si=OxRPJIx2wBKkf8LX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/1BsVhumGlNc?si=F8d5cizzV_kBfQ_4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/CyRlWlaJnTY?si=SFzxNpEBBGJC6ioq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/tLBlhp0SA_0?si=r23Wq3x0rkypyH7H" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/vnnlUCLfn6I?si=UI6KgNRQmzWutD3M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/vlAWzsGd-Yk?si=yktQ6fD75QV5EYtM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/XZwBNDGuWGU?si=aDd07AtzbMvq_Hwk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </main>
    <footer>
        <p>Copyright by Harry | It will be crime if you don't tell your friends about this train</p>
        <p>Director : Vivaan Yadav , Shout out please.</p>
    </footer>
</body>
</html>

CSS

h1{
    text-align: center;
    border : 2px solid green;
    padding : 8px;
    margin: 4px;
    background-color: green;
}
h2{

    color: aqua;
}
body{
    background-color: black;
}
p{
    color: white;
}

**Comment by 9199sk** [comment]
### hai video
