### ISSUE TITLE
No Proper ReadMe instructions

### ISSUE THREAD

**Issue by harsh432004** [CodeWithHarry/Sigma-Web-Dev-Course#18]
In this repo no proper instructions are given in ReadMe File, here is complete ReadMe File
# Sigma Web Dev Course

Welcome to the Sigma Web Development Course! 🚀

This is a comprehensive full-stack web development course created by Harry from CodeWithHarry.

## Course Overview

This course covers everything you need to know to become a skilled web developer, from the basics of HTML and CSS to advanced topics like JavaScript frameworks, server-side development, and more.

## Connect with CodeWithHarry

Stay updated with the latest web development tutorials, tips, and news by connecting with CodeWithHarry on social media:

- **YouTube:** [CodeWithHarry YouTube](https://www.youtube.com/@CodeWithHarry)
- **Website:** [CodeWithHarry](https://www.codewithharry.com)
- **FaceBook:** [@CodeWithHarry](https://www.facebook.com/CodeWithHarry)
- **Instagram:** [@CodeWithHarry](https://www.instagram.com/codewithharry)

## Course Curriculum

You can find the complete course curriculum and materials in the [course repository](https://github.com/CodeWithHarry/Sigma-Web-Dev-Course.git).

## Getting Started

To get started with the course, clone this repository on your desktop:

```bash
git clone https://github.com/CodeWithHarry/Sigma-Web-Dev-Course.git

**Comment by Shubhu1134** [comment]
i dindt found issue
