### ISSUE TITLE
Video 12 exercise 

### ISSUE THREAD

**Issue by vineet452** [CodeWithHarry/Sigma-Web-Dev-Course#20]
https://gist.github.com/vineet452/2b7bba5977712c9b7827aa52cc347fa9

**Comment by Saurabh-Punera** [comment]
<head>
    <h1>Exercise 1: Media Player</h1>
</head>
<Main>
    
    <h2>Immerse Yourself in a Visual Wonderland: Explore Our Captivating Videos</h2>
    <video src="mp4_1.mp4" controls muted loop height="250" width="250"></video>
    <video src="mp4_2.mp4" controls muted loop height="250" width="250"></video>
    <video src="mp_3.mp4" controls muted loop height="250" width="250"></video>
    <div>
        <iframe width="250" height="250" src="https://www.youtube.com/embed/tVzUXW6siu0?si=513suWeN1rkhYStH"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen></iframe>
        <iframe width="250" height="250" src="https://www.youtube.com/embed/kJEsTjH5mVg?si=p8lldXa5StHPxMKM"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen></iframe>
        <iframe width="230" height="250" src="https://www.youtube.com/embed/BGeDBfCIqas?si=IPoGiqCj7F8syrI9"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen></iframe>
    </div>
    <h2>Unlock the Soundscapes: Dive into an Auditory Odyssey with Our Audio Collection</h2>
    <div>
        <Caption>Audio 1</Caption>
        <audio src="mp1.mp3" controls></audio>
    </div>
    <div>
        <Caption>Audio 2</Caption><audio src="mp2.mp3" controls></audio>
    </div>
    <div>
        <Caption>Audio 3</Caption><audio src="mp3.mp3" controls></audio>
    </div>
    <div>
        <Caption>Audio 4</Caption><audio src="mp4.mp3" controls></audio>
    </div>
    <div>
        <Caption>Audio 5</Caption><audio src="mp5.mp3" controls></audio>
    </div>
    <div>
        <Caption>Audio 6</Caption><audio src="Pikachu Sms Ringtone Download.mp3" controls></audio>
    </div>
    </div>
</Main>
<br>
<Footer>
    <h4>Copyright@ 2023 | All Rights Reserved </h4>
</Footer>

**Comment by Saurabh-Punera** [comment]
https://github.com/CodeWithHarry/Sigma-Web-Dev-Course/commit/c061c22e6ec27ae44b8620350a0a8e32eee9531a#commitcomment-129406664

**Comment by Gaurav1073** [comment]
https://github.com/Gaurav1073/Exercise

**Comment by Vivaan1st** [comment]
https://github.com/Vivaan1st/Coding.git

**Comment by Cyber-Warrior1** [comment]
https://gist.github.com/Cyber-Warrior1/8ce576ed0aef8fc144e26bbfdeaebe87

**Comment by prakashvishal93** [comment]
https://github.com/prakashvishal93/Sigma-Web-Dev/blob/main/Video-12/index.html

**Comment by shreekantha3** [comment]
https://github.com/shreekantha3/Sigma-Web-Development/blob/main/video12/index.html

**Comment by codyandersan** [comment]
https://replit.com/@codyandersan/Sigma-Challenge-1

**Comment by SigmaMichaeldesanta** [comment]
[https://github.com/SigmaMichaeldesanta/Sigma/blob/main/Exercise.html](url)
