### ISSUE TITLE
facing this error in Video 84 Spotify clone 

### ISSUE THREAD

**Issue by naveenyadav56** [CodeWithHarry/Sigma-Web-Dev-Course#219]
GET http://127.0.0.1:5500/Song/Song/info.json 404 (Not Found)
displayAlbums @ index.js:86
await in displayAlbums
main @ index.js:125
await in main
(anonymous) @ index.js:211Understand this error
VM918:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by koushikrai** [comment]
u can refer my Spotify clone project I had solved it

**Comment by naveenyadav56** [comment]
send me the link bro

**Comment by ayush2131** [comment]
i am facing the same error did you solved it

**Comment by naveenyadav56** [comment]
> i am facing the same error did you solved it

no did you solved that

**Comment by 2nithin2** [comment]
> > i am facing the same error did you solved it
> 
> no did you solved that

what's the problem explain me clearly i will try to solve?

**Comment by naveenyadav56** [comment]
> what's the problem explain me clearly i will try to solve?
the albums are not loading all things are work properly

**Comment by naveenyadav56** [comment]
> i am facing the same error did you solved it

yes
