### ISSUE TITLE
Exercise 1 Solution

### ISSUE THREAD

**Issue by Code-With-Devansh** [CodeWithHarry/Sigma-Web-Dev-Course#32]
https://github.com/Code-With-Devansh/Exercise-1-MediaPlayer.git

**Comment by vivek63800** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> practice work-1</title>
</head>
<body>
   
   <h1>This is video File</h1>
   <video src="1 (1).mp4" controls muted height="150px" weight="200"></video>
   
   <video src="1 (2).mp4" controls muted height="150px" weight="200"></video>

   <video src="1 (3).mp4"controls muted height="150px" weight="200"></video>
   <br>
   <video src="1 (4).mp4"controls muted height="150px" weight="200"></video>

   <video src="1 (5).mp4"controls muted height="150px" weight="200"></video>

   <video src="6.mp4.mp4"controls muted height="150px" weight="200"></video>
   
   <h2>This is audio book</h2>
   <audio src="audio1.mp3 (2).mp3"controls muted height="250px" weight="200"></audio>
<audio src="audio2.mp3 (1) - Copy.mp3"controls muted height="250px" weight="200"></audio>
<audio src="audio3.mp3.mp3"controls muted height="250px" weight="200"></audio> 
<audio src="audio1.mp3 (2) - Copy.mp3"controls muted height="250px" weight="200"></audio>  
<audio src="audio3.mp3 - Copy.mp3"controls muted height="250px" weight="200"></audio>
<audio src="audio2.mp3 (1).mp3"controls muted height="250px" weight="200"></audio> 
</body>
</html>

**Comment by iman1214** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music & Movies</title>
</head>

<body>
    <header>
        <h1>Welcome to Music & Movies</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed minima temporibus veniam iusto voluptatum
            provident neque quam rem porro libero.</p>
        <h3>search for more</h3>
        <form action="#">
            <label for="Search">Search</label>
            <input type="text" name="Search" id="search">
        </form>
        <nav>
            <ul>
                <li>movies</li>
                <li>music</li>
                <li>services</li>
            </ul>
        </nav>
        <div>
            <video src="1.mp4.MOV" controls width="200" height="400"></video>
            <video src="2.mp4.MOV" controls width="200" height="400"></video>
            <video src="3.mp4.MOV" controls width="200" height="400"></video>
            <video src="4.mp4.MOV" controls width="200" height="400"></video>
            <video src="5.mp4.MOV" controls width="200" height="400"></video>
            <video src="6.mp4.MOV" controls width="200" height="400"></video>
        </div>
        <div>
            <audio src="Mann Mera.mp3.mp3" controls></audio>
            <audio src="Mushk.mp3.mp3" controls></audio>
            <audio src="safar.mp3.mp3" controls></audio>
            <audio src="sanson ki mala pe instrumental.mp3.mp3" controls></audio>
            <audio src="Shayad.mp3.mp3" controls></audio>
            <audio src="Tere Hawaale.mp3.mp3" controls></audio>
        </div>
    </header>
    <main>
        <p>for more websites like this:</p>
    </main>
    <footer>
        <a target="_blank" href="https://www.google.com">Open google</a> <br>
        <a target="_blank" href="https://www.instagram.com">Open instagram</a>
    </footer>
</body>
</html>

**Comment by iman1214** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music & Movies</title>
</head>

<body>
    <header>
        <h1>Welcome to Music & Movies</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed minima temporibus veniam iusto voluptatum
            provident neque quam rem porro libero.</p>
        <h3>search for more</h3>
        <form action="#">
            <label for="Search">Search</label>
            <input type="text" name="Search" id="search">
        </form>
        <nav>
            <ul>
                <li>movies</li>
                <li>music</li>
                <li>services</li>
            </ul>
        </nav>
        <div>
            <video src="1.mp4.MOV" controls width="200" height="400"></video>
            <video src="2.mp4.MOV" controls width="200" height="400"></video>
            <video src="3.mp4.MOV" controls width="200" height="400"></video>
            <video src="4.mp4.MOV" controls width="200" height="400"></video>
            <video src="5.mp4.MOV" controls width="200" height="400"></video>
            <video src="6.mp4.MOV" controls width="200" height="400"></video>
        </div>
        <div>
            <audio src="Mann Mera.mp3.mp3" controls></audio>
            <audio src="Mushk.mp3.mp3" controls></audio>
            <audio src="safar.mp3.mp3" controls></audio>
            <audio src="sanson ki mala pe instrumental.mp3.mp3" controls></audio>
            <audio src="Shayad.mp3.mp3" controls></audio>
            <audio src="Tere Hawaale.mp3.mp3" controls></audio>
        </div>
    </header>
    <main>
        <p>for more websites like this:</p>
    </main>
    <footer>
        <a target="_blank" href="https://www.google.com">Open google</a> <br>
        <a target="_blank" href="https://www.instagram.com">Open instagram</a>
    </footer>
</body>
</html>
