### ISSUE TITLE
Exercise #1 Solution

### ISSUE THREAD

**Issue by codyandersan** [CodeWithHarry/Sigma-Web-Dev-Course#37]
Here is my solution:—
```html
<!DOCTYPE html>
<html>

<head>
<meta name="author" content="Prakhar Aditya Tripathi">
<meta charset="UTF-8">
<meta name="description" content="Media Player">
<meta name="keywords" content="Sigma Challenge #1">
<meta name="author" content="Prakhar Aditya Tripathi">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HTML Media Player</title>

</head>

<body>

<h1>
Media Player
</h1>

<h2>
Videos:
</h2>

<div class="videos">
<table>
<tr>
<td><video controls src="1.mp4" width="300" height="200"></td>
<td><video controls src="2.mp4" width="300" height="200"></td>
<td><video controls src="3.mp4" width="300" height="200"></td>
</tr>
  
<tr>
<td><video controls src="4.mp4" width="300" height="200"></td>
<td><video controls src="5.mp4" width="300" height="200"></td>
<td><video controls src="6.mp4" width="300" height="200"></td>
</tr>
</table>



<h2>
Audios:
</h2>

<div class="audios">
<table>
<tr>
<td><audio controls src="1.mp3" width="300"></td>
<td><audio controls src="2.mp3" width="300"></td>
<td><audio controls src="3.mp3" width="300"></td>
</tr>
  
<tr>
<td><audio controls src="4.mp3" width="300"></td>
<td><audio controls src="5.mp3" width="300"></td>
<td><audio controls src="6.mp3" width="300"></td>
</tr>
  
</table>
</div>

</body>
</html>
```

https://replit.com/@codyandersan/Sigma-Challenge-1

P.S.: I do not know how to submit my code, so I am sharing it in this issue. Apologies if this is not the correct mode of submission.

(Today's my birthday!)

**Comment by SigmaMichaeldesanta** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Media Player</title>
</head>

<body>

    <div>
        <h1><u>
                <center>Media Player Website</center>
            </u></h1>
    </div>
    <div>
        <h1>Table of contents</h1>
    </div>
        <h2>This is a sample Media player website Made by me. This is the answer of the <u>Exercise 1</u> given by
            CodewithHarry
        </h2>
    </div>
    <div>
        <h2 id="video-section">Videos</h2>
    </div>
    <Div>
        <video width="250px" height="350px" src="Car.mp4" controls>Car edit</video>
        <video width="250px" height="350px" src="Nissangtr.mp4" controls>GTR edit</video>
        <video width="250px" height="350px" src="Napoleon.mp4" controls>Napoleon edit</video>
        <video width="250px" height="350px" src="Saulgoodman.mp4" controls>Saulgoodman edit</video>
        <video width="250px" height="350px" src="Optimus Prime.mp4" controls>Optimisprime edit</video>
        <video width="250px" height="350px" src="MarioKingsman.mp4" controls>MarioKingsman</video>
    </Div>
    <div>
        <h2><u>Audios</u></h2>
    </div>
    <table>
        <tr>
            <th>Sound name</th>
            <th>Sound</th>
        </tr>
        <tr>
            <td>
                What the hell Oh my God no Way Sound Effect</td>
            <td><audio src="What the hell Oh my God no Way Sound Effect [q9zKYh8sY_E].mp3" controls>What the hell Oh my
                    God no Way Sound Effect</audio>
            </td>
        </tr>
        <tr>
            <td>Tu Tu Tu Sound Effect</td>
            <td><audio src="TU TU TU TU TU     TU     TU TU TU TU TU [vqleLVVWWNE].mp3" controls>Tu Tu Tu Sound
                    Effect</audio>
            </td>
        </tr>
        <tr>
            <td>
                Modi Zee Sound Effect</td>
            <td><audio src="Narendra Modi - Cheques (Official Audio) [TubeRipper.com].mp3" controls>Modi Zee Sound
                    Effect</audio>
            </td>
        </tr>
        <tr>
            <td>
                Aw hell nawh man WTF man Sound Effect</td>
            <td><audio src="omg bruh oh hell Naw man wtf man [31GRu9OYuVM].mp3" controls>Aw hell nawh man WTF man Sound
                    Effect</audio>
            </td>
        </tr>
        <tr>
            <td>
                bruh Sound Effect</td>
            <td><audio src="Bruh (sound effect) [h5yvbPmxuZM].mp3" controls>bruh Sound Effect</audio>
            </td>
        </tr>
        <tr>
            <td>
                Ringtone</td>
            <td><audio src="otnicka peaky.mp3" controls>Ringtone Sound Effect</audio>
            </td>
        </tr>

    </table>
</body>

</html>

**Comment by AnubhavSC** [comment]
<body>
    <h1>Media Files</h1>

    <h2>Audio Files</h2>
    <ul>
        <li>
            <audio controls>
                <source src="1.mp3">
                Your browser does not support the audio element.
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="2.mp3" >
                Your browser does not support the audio element.
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="3.mp3" >
                Your browser does not support the audio element.
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="4.mp3" >
                Your browser does not support the audio element.
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="5.mp3" >
                Your browser does not support the audio element.
            </audio>
        </li>
         <li>
            <audio controls>
                <source src="6.mp3" >
                Your browser does not support the audio element.
            </audio>
        </li>
    </ul>
    <h2>Video Files</h2>
    <ul>
        <li>
            <video controls>
                <source src="1.mp4">
                Your browser does not support the video element.
            </video>
        </li>
        <li>
            <video controls>
                <source src="2.mp4">
                Your browser does not support the video element.
            </video>
        </li>
          <li>
            <video controls>
                <source src="3.mp4">
                Your browser does not support the video element.
            </video>
        </li>
         <li>
            <video controls>
                <source src="4.mp4">
                Your browser does not support the video element.
            </video>
        </li>
         <li>
            <video controls>
                <source src="5.mp4">
                Your browser does not support the video element.
            </video>
        </li>
         <li>
            <video controls>
                <source src="6.mp4">
                Your browser does not support the video element.
            </video>
        </li>
    </ul>
</body>

**Comment by AnubhavSC** [comment]
<body>
    <h1>Media Files</h1>

    <h2>Audio Files</h2>
    <ul>
        <li>
            <audio controls>
                <source src="1.mp3">
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="2.mp3" >
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="3.mp3" >
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="4.mp3" >
            </audio>
        </li>
        <li>
            <audio controls>
                <source src="5.mp3" >
            </audio>
        </li>
         <li>
            <audio controls>
                <source src="6.mp3" >
            </audio>
        </li>
    </ul>
    <h2>Video Files</h2>
    <ul>
        <li>
            <video controls>
                <source src="1.mp4">
            </video>
        </li>
        <li>
            <video controls>
                <source src="2.mp4">
            </video>
        </li>
          <li>
            <video controls>
                <source src="3.mp4">
            </video>
        </li>
         <li>
            <video controls>
                <source src="4.mp4">
            </video>
        </li>
         <li>
            <video controls>
                <source src="5.mp4">
            </video>
        </li>
         <li>
            <video controls>
                <source src="6.mp4">
            </video>
        </li>
    </ul>
</body>

**Comment by TiwariBro** [comment]
⭐⭐

**Comment by RijaSyed** [comment]
Here is my Solution please guide me more about this solution Thanks ...
<body>
<h1>
        <ul>
            <li><audio src="Audio1.mp3" controls autoplay></audio></li>
            <li><video src="video1.mp4" controls autoplay></video></li>
        </ul>
    </h1>
    <h1>
        <ul>
            <li><audio src="Audio2.mp3" controls loop></audio></li>
            <li><video src="video2" controls loop></video></li>
        </ul>
    </h1>
    <h1>
        <ul>
            <li><audio src="Audio3" controls muted></audio></li>
            <li><video src="Audio3" controls muted></video></li>
        </ul>
    </h1>
    <h1>
        <ul>
            <li><audio src="Audio4" controls preload="auto"></audio></li>
            <li><video src="Audio4" controls preload="auto"></video></li>
        </ul>
    </h1>
    <h1>
        <ul>
            <li><audio src="Audio5" controls preload="metadata"></audio></li>
            <li><video src="Audio5" controls preload="metadata"></video></li>
        </ul>
    </h1>
    <h1>
        <ul>
            <li><audio src="Audio6" controls preload="none"></audio></li>
            <li><video src="Audio6" controls preload="none"></video></li>
        </ul>
    </h1>

</body>
