### ISSUE TITLE
Exercise Solution Day 12 Videos and audios

### ISSUE THREAD

**Issue by Babapistol** [CodeWithHarry/Sigma-Web-Dev-Course#41]
here is my html code sir.
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Videos and Audios</title>
</head>

<body>

    <h1>Videos</h1>
    <div>
        <video src="videos/1.mp4" controls height="185"></video>
        <video src="videos/2.mp4" controls height="185"></video>
        <video src="videos/3.mp4" controls height="185"></video>
        <video src="videos/4.mp4" controls height="185"></video>
        <video src="videos/5.mp4" controls height="185"></video>
        <video src="videos/5.mp4" controls height="185"></video>
    </div>
    <h1>Audios</h1>
    <div>
        <audio src="audios/1.mp3" controls></audio>
        <audio src="audios/2.mp3" controls></audio>
        <audio src="audios/3.mp3" controls></audio>
        <audio src="audios/4.mp3" controls></audio>
        <audio src="audios/5.mp3" controls></audio>
        <audio src="audios/6.mp3" controls></audio>
    </div>

</body>

</html>

NOTE: If anyone using this code make sure that create two folders with the names of audios and videos and then add 6 mp4 files on videos folder as same as add 6 mp3 files on audio folder

**Comment by DhanjitNath** [comment]
Challenge Completed! 
Here's My Code #HarryBhai :- 

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>HTML Media Player </title>

</head>

<body>
  <h1> A simple Media Player </h1>
  <div class="videos">
    <h2>Videos</h2>
    <div class="CodingVideos">
      <h3>Coding Videos </h3>
      <video src="1.mp4 controls">1.mp4</video>
      <video src="2.mp4 controls">2.mp4</video>
      <video src="3.mp4 controls">3.mp4</video>
    </div>

    <div class="FunnyVideos">
      <h3>Funny Videos</h3>
      <video src="4.mp4 controls">4.mp4</video>
      <video src="5.mp4 controls">5.mp4</video>
      <video src="6.mp4 controls">6.mp4</video>
    </div>
  </div>
  <div class="audios">
    <h2>Audio </h2>
    <div class="NCS">
      <h3>NCS - Non Copyright Songs</h3>
      <audio controls>
        <source src="1.mp3" type="audio/mpeg">
      </audio>
      <audio controls>
        <source src="2.mp3" type="audio/mpeg">
      </audio>
      <audio controls>
        <source src="3.mp3" type="audio/mpeg">
      </audio>
      <audio controls>
        <source src="4.mp3" type="audio/mpeg">
      </audio>
      <audio controls>
        <source src="5.mp3" type="audio/mpeg">
      </audio>
      <audio controls>
        <source src="6.mp3" type="audio/mpeg">
      </audio>
    </div>
  </div>

  <footer>
    <pre>
   If you are reading this. I would like to clarify that :-
   1.I have Build This Website Using Mobile using SPCK Editor app 
   2. Audio and video will working If we add those files. 
   3. #SigmaBatchOp. Thanks Harry Bhai. The curse is Helpful! 
  </pre>
  </footer>
</body>

</html>

**Comment by farhankhan078** [comment]
<!DOCTYPE html>
<html>
   <head>
       <title>
             Exercise 1 Sigma Batch OP
       </title>
   </head>
<body>

<h1>Videos</h1>
<div>
    <video src="videos/1.mp4" controls height="190"></video>
    <video src="videos/2.mp4" controls height="190"></video>
    <video src="video/3.mp4" controls height="190"></video>
    <video src="videos/4.mp4" controls height="190"></video>
    <video src="videos/5.mp4" controls height="190"></video>
    <video src="videos/5.mp4" controls height="190"></video>

</div>
<h1>MP3 Song</h1>
<div>
    <audio src="audios/1.mp3" controls></audio>
    <audio src="audios/2.mp3" controls></audio>
    <audio src="audios/3.mp3" controls></audio>
    <audio src="audios/4.mp3" controls></audio>
    <audio src="audios/5.mp3" controls></audio>
    <audio src="audios/6.mp3" controls></audio>
</div>
<pre>.                               thank you Harry Bhai</pre>
</body>
</html>
