### ISSUE TITLE
Solution of Exercise 1

### ISSUE THREAD

**Issue by Avi1305** [CodeWithHarry/Sigma-Web-Dev-Course#46]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercise 1 -> Let's Do IT!</title>
</head>

<body>
    <h1>Category</h1>
    <h2>
        <label for="video">Videos</label>
        <input type="radio" id="video" name="Video" value="video">

        <label for="video">Audio</label>
        <input type="radio" id="video" name="Video" value="audio">
    </h2>

        <h2>Videos</h2>
        <h3>
            <ol type="I">
                <li>Video1</li>
                <div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                    <svg height="100" width="100">
                        <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
                    </svg>
                </div>
                <li>Video2</li>
                <div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                </div>
                <li>Video3</li>
                <div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                </div>
                <li>Video4</li><div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                </div>

                <li>Video5</li>
                <div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                </div>
                <li>Video6</li>
                <div>
                    <video src="video.mp4" height="200" controls  poster="png.png"></video>
                </div>
            </ol>
        </h3>
        <h2>Audios</h2>
        <h3>
            <ol type="i">
                <li>Audio1</li>
                <audio src="sachin.mp3" controls ></audio>
                <li>Audio2</li>
                <audio src="sachin.mp3" controls ></audio>
                <li>Audio3</li>
                <audio src="sachin.mp3" controls ></audio>
                <li>Audio4</li>
                <audio src="sachin.mp3" controls ></audio>
                <li>Audio5</li>
                <audio src="sachin.mp3" controls ></audio>
                <li>Audio6</li>
                <audio src="sachin.mp3" controls ></audio>
        </h3>
        </ol>
</body>

</html>

**Comment by shreekantha3** [comment]
Why are you adding all videos in <h3 ></h3> tags
