### ISSUE TITLE
Exercise 2

### ISSUE THREAD

**Issue by Dassuvam** [CodeWithHarry/Sigma-Web-Dev-Course#59]
<style>
        
        p:first-child{
            background-color: yellow;
            color: red;
            font-family: 'Tilt Neon', sans-serif;
        }
        p{
            background-color: blue;
            color: white;
            font-family: 'Tilt Neon', sans-serif;

        }
    </style>

**Comment by oyepriyansh** [comment]
correct

**Comment by Dassuvam** [comment]
Thanks bro for checking
