### ISSUE TITLE
video 5 issue

### ISSUE THREAD

**Issue by kaushik77777** [CodeWithHarry/Sigma-Web-Dev-Course#6]
in video 5 i have written the code as it is but its all getting printed in row cant able to recognize where the mistake please Harry vaiya clarify
 

output:   Name Age Harry 100 like this

**Comment by authreborn** [comment]
> in video 5 i have written the code as it is but its all getting printed in row cant able to recognize where the mistake please Harry vaiya clarify
> 
> output: Name Age Harry 100 like this

For more clarification can you provide the source code ?

**Comment by vedant2506** [comment]
> in video 5 i have written the code as it is but its all getting printed in row cant able to recognize where the mistake please Harry vaiya clarify
>  
> 
> output:   Name Age Harry 100 like this

Just copy paste your source code and problem to chatgpt you will get your solution

**Comment by suzt-0** [comment]
> in video 5 i have written the code as it is but its all getting printed in row cant able to recognize where the mistake please Harry vaiya clarify
> 
> output: Name Age Harry 100 like this

**Comment by suzt-0** [comment]
Check if you have included everything in same <tr> tag like 
<table>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <td>harry</td>
                <td>25</td>
            </tr>

 </table>
then the result will be something like : Name	Age	harry	25
To make it in table format try separating the "table heading" and "table data" in separate <tr> tag like:
<table>
            <tr>
                <th>Name</th>
                <th>Age</th>
            </tr>
            <tr>
                <td>harry</td>
                <td>25</td>
            </tr>

        </table>

**Comment by suzt-0** [comment]
I think you just tried to include table heading and table data in same <tr> tag like:
![image](https://github.com/CodeWithHarry/Sigma-Web-Dev-Course/assets/103885610/20382fc8-15fb-4de5-a584-769f381b2e35)
It will result in some thing like: Name	Age	harry	25

Try separating "table heading" and "table data" in separate <tr> tag like:
![image](https://github.com/CodeWithHarry/Sigma-Web-Dev-Course/assets/103885610/f86df8a6-5553-469e-95ec-7260fc39d06f)
result will be like : 
Name	Age
harry	25

**Comment by suzt-0** [comment]
> in video 5 i have written the code as it is but its all getting printed in row cant able to recognize where the mistake please Harry vaiya clarify
> 
> output: Name Age Harry 100 like this

I think you just tried to include table heading and table data in same <tr> tag like:
![image](https://github.com/CodeWithHarry/Sigma-Web-Dev-Course/assets/103885610/20382fc8-15fb-4de5-a584-769f381b2e35)
It will result in some thing like: 

<table>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <td>harry</td>
                <td>25</td>
            </tr>
        </table>


Try separating "table heading" and "table data" in separate <tr> tag like:
![image](https://github.com/CodeWithHarry/Sigma-Web-Dev-Course/assets/103885610/f86df8a6-5553-469e-95ec-7260fc39d06f)
result will be like : 
<table>
            <tr>
                <th>Name</th>
                <th>Age</th>
            </tr>
            <tr>
                <td>harry</td>
                <td>25</td>
            </tr>
        </table>
