### ISSUE TITLE
Video-7 issue

### ISSUE THREAD

**Issue by suzt-0** [CodeWithHarry/Sigma-Web-Dev-Course#9]
I just started 3 days ago so I don't have much idea but this course has been a blessing to me. Thank u so much for this course and words cannot explain how much this course has helped me.

 Now the main issue,
is this 
 `<form action= "post">`
correct.
I looked up in web and something like this came up,
`<form action="/action_page.php" method="post">`

If there is any difference please explain : )

**Comment by amanverma2009** [comment]
Its The `<form action="/action_page.php" method="post">` Action Attribute have links as values. Method Attrribute Has Commonly Post Or Get as Value.
Hope This Helps.

**Comment by suzt-0** [comment]
Thank you 😊

**Comment by codyandersan** [comment]
> Thank you 😊

If your doubt is cleared, please mark this issue as closed.
